services:
  - type: web
    name: vayusatya-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OWM_API_KEY
        sync: false
